<?php

declare(strict_types=1);

namespace Directus\Providers;

use Directus\Events\SettingChanged;
use Directus\Listeners\ClearSettingsCache;
use Illuminate\Foundation\Support\Providers\EventServiceProvider;

/**
 * Events provider.
 */
class EventsProvider extends EventServiceProvider
{
    protected $listen = [
        SettingChanged::class => [
            ClearSettingsCache::class,
        ],
    ];

    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
